title: BumbleBrain
author: Andrew N.S. Ernest, Ph.D., P.E., BCEE, D.WRE
logo: AndrewErnest.png
only_build_toc_files: true
execute:
  execute_notebooks: force
sphinx:
  extra_extensions:
  # - 'sphinx.ext.autodoc'
  # - 'ablog'
  # - 'sphinx.ext.todo'
  # - 'sphinx.ext.autosummary'
  # crashes jupyter-build
  # - 'sphinxcontrib.bibtex'
# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
  # - references.bib