[tool.poetry]
name = "rgvflood"
version = "0.1.0"
description = "Lower Rio Grande Valley Flood Management"
authors = ["Andrew Ernest <anernest@ratesresearch.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
invoke = "^1.7.1"
Sphinx = "^5.1.1"
Jinja2 = "^3.1.2"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-bibtex = "^2.4.2"
sphinxcontrib-plantuml = "^0.24"
python-dotenv = "^0.20.0"
sphinxcontrib-mermaid = "^0.7.1"
sphinx-revealjs = "^2.0.1"
spyce = {git = "https://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@github.com/RATESResearch/Spyce.git", rev = "main"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
