# https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ${NAMESPACE}-backendconfig
  namespace: ${NAMESPACE}
spec:
  customRequestHeaders:
    headers:
    - "X-Forwarded-Proto:https"
  healthCheck:
    checkIntervalSec: 15
    # timeoutSec: 30
    # healthyThreshold: 2
    # unhealthyThreshold: 2
    type: HTTP
    requestPath: /
    # port: 80
    # https://stackoverflow.com/questions/69277599/zonal-network-endpoint-group-unhealthy-even-though-that-container-application-wo
    port: 8001