gantt
dateFormat  YYYY-MM
axisFormat %Y
title Data Collection & Assimilation
excludes weekends

section Develop Data Dictionary
End User Data Dictionary Workshop: done, datadict, 2021-10, 2021-12
RTHS Data Model: done, rthsdm, 2021-11, 2022-01
Field Survey Data Model: done, fsdm, 2022-03, 2022-05
Hydraulic Asset Inventory Data Model:done, hasidm, 2022-04, 2022-06
section Survey Preparation
Delineate watershed (GIS): done, dw, 2021-03, 2021-10
Validate watershed delineations (GIS): done, vwd, 2021-05, 2021-11
Initial LRGV Flood Map Development (GIS): done, ilfmd, 2021-07, 2021-11
Initial RTHS Site identification (GIS): done, irsi, 2021-08, 2021-12
Reconnaissance- RTHS: done, recon, 2022-02, 2022-04
Horizontal RTHS Transect Extent: done, transect, 2022-03, 2022-05
Site Access Instrument Submittal: access_submit, 2022-05, 2022-08
Site Access Approval: access_approval, 2022-08, 2022-12
Develop LRGV Water Resources Field Survey Manual:done, access_approval, 2022-03, 2022-05
section Field Surveys
RTHS Transect Surveys: rths_transect, 2022-08, 2022-12 
Other Hydraulic Asset Surveys: other_survey, 2022-08, 2022-12
section Hydrologic Data Collection
State & National Data Assimilations:done, natl, 2022-01, 2022-02
Existing Local Data Collection:done, local, 2021-11, 2022-03
Data & Model Framework Fabrication: model, 2021-12, 2023-01