gantt
dateFormat  YYYY-MM
axisFormat %Y-%m
title Database Enhancements 
excludes weekends

RTHS Data Integration Upgrade: done, rdiu, 2021-03, 2021-10
Survey Data Integration into Database: sdid, 2022-08, 2022-10
Hydraulic Asset Integration Completion Report: hai, 2022-10, 2022-12
Crowd Source Data Integration Process Definition: done, csdipd, 2022-05, 2022-07
Hydrologic Data Assimilation into Database: done, hdad, 2022-04, 2022-06






