gantt
dateFormat  YY-Q
axisFormat %y-%m
title RGVFlood Development Plan
excludes weekends

section Regional Hydrology and Hydraulics
Data Collection & Assimilation  :active, dca, 21-1, 24-4
Regional Modeling               :active, rm, 22-1, 23-2
Sub-Regional Modeling           :active, srm, 22-2, 23-3
Urban Modeling                  :um, 22-3, 24-1
section Real Time Hydrologic Stations
Installation & Provisioning, Year 1 :rthsy1, 22-4, 23-4
Operation & Maintenance, Year 2 :rthsy2, 23-4, 24-4
Operation & Maintenance, Year 3 :rthsy3, 24-4, 25-4
section REON.cc Cyberinfrastructure
User Interface Enhancements : uie, 21-4, 22-2
Model Integration : me, 22-1, 22-4
Database Enhancements : de, 21-4, 22-4
Click rm href "RegionalHandH"