gantt
dateFormat  YYYY-MM
axisFormat %Y-%m
title Model Integration
excludes weekends

section Tier I
Requirements Determination:done, t1ird, 2022-03, 2022-04
Implementation:done, t1ii, 2022-04, 2022-06
Deployment:t1id, 2022-06, 2022-08
section Tier II
Requirements Determination:done, t2ird, 2022-04, 2022-05
Implementation:done, t2ii, 2022-05, 2022-07
Deployment:t2id, 2022-08, 2022-10
section Tier III
Requirements Determination:t3ird, 2022-09, 2022-11
Implementation:t3ii, 2022-11, 2023-03
Deployment:t3id, 2023-03, 2023-07




