gantt
dateFormat  YYYY-MM
axisFormat %Y
title Regional Modeling
excludes weekends

section Tier 1 Real Time Hydrologic Model Development
IBWC Floodway                   :ibwcdev, 2022-06, 2022-11 
Hidalgo/Willacy Drain           :hwmddev, 2022-06, 2022-11
Raymondville Drain              :rvddev, 2022-04, 2022-08
Rio Grande/Arroyo Colorado      :acdev, 2022-06, 2022-11
Brownsville Ship Channel        :bscdev, 2022-04, 2022-08
section Tier 1 Real Time Hydrologic Model Instantiation
IBWC Floodway                   :ibwcins, 2022-10, 2023-02
Hidalgo/Willacy Drain           :hwmdins, 2022-10, 2023-02
Raymondville Drain              :rvdins, 2022-06, 2022-10
Rio Grande/Arroyo Colorado      :acins, 2022-10, 2023-02
Brownsville Ship Channel        :bscdev, 2022-06, 2022-10
