gantt
dateFormat  YYYY-MM
axisFormat %y-%m
title RGVFlood Development Plan
excludes weekends

section Regional Hydrology and Hydraulics
Data Collection & Assimilation  :active, dca, 2021-03, 950d
Regional Modeling               :active, rm, 2022-01, 2023-06
Sub-Regional Modeling           :active, srm, 2022-02, 2023-08
Urban Modeling                  :um, 2022-08, 2024-03
section Real Time Hydrologic Stations
Installation & Provisioning, Year 1 :rthsy1, 2022-10, 2023-06
Operation & Maintenance, Year 2 :rthsy2, 2023-06, 2024-06
Operation & Maintenance, Year 3 :rthsy3, 2024-01, 2024-10
section REON.cc Cyberinfrastructure
User Interface Enhancements :done, uie, 2021-12, 2022-06
Model Integration : me, 2022-01, 2023-06
Database Enhancements :done,  de, 2021-03, 2022-12


