gantt
dateFormat  YYYY-MM
axisFormat %y-%m
title Real Time Hydrologic Stations
excludes weekends

Data Collection & Assimilation  :active, dca, 2021-03, 950d
Regional Modeling               :active, rm, 2022-01, 2023-06
Installation & Provisioning, Year 1 :rthsy1, 2022-10, 2023-06
Operation & Maintenance, Year 2 :rthsy2, 2023-06, 2024-06
Operation & Maintenance, Year 3 :rthsy3, 2024-01, 2024-10
Model Integration :active, me, 2022-01, 2023-06