gantt
dateFormat  YYYY-MM
axisFormat %Y
title Sub-Regional Modeling
excludes weekends

section  Tier 2 On-Demand Sub-Regional Hydraulic Model Development - Sub-Basin
Raymondville Drain: done, ibwc, 2022-02, 2022-03
Bronsville Ship Channel: done, ibwc, 2022-03, 2022-04
Hidalgo Drain (Delta Area): done, ibwc, 2022-04, 2022-05
IBWC Floodway (Santa Monica): done, ibwc, 2022-05, 2022-06
TBD5: done, ibwc, 2022-06, 2022-07
TBD6: done, ibwc, 2022-06, 2022-07
section  Tier 2 On-Demand Sub-Regional Hydraulic Model Validation - Sub-Basin
Raymondville Drain: ibwc, 2022-06, 2022-07
Bronsville Ship Channel: ibwc, 2022-06, 2022-07
Hidalgo Drain (Delta Area): ibwc, 2022-07, 2022-08
IBWC Floodway (Santa Monica): ibwc, 2022-07, 2022-08
TBD5: ibwc, 2022-08, 2022-09
TBD6: ibwc, 2022-08, 2022-09