gantt
dateFormat  YYYY-MM
axisFormat %Y-%m
title User Interface Enhancements
excludes weekends

Requirements Determination: done, rd, 2021-10, 2021-11
Requirements Validation: done, rv, 2021-11, 2021-12
Predevelopment Plan: done, pp, 2021-12, 2022-01
Implementation: done, imp, 2022-01, 2022-02
Quality Assurance Demonstration: done, qad, 2022-02, 2022-03
End-User Acceptance Testing: done, euat, 2022-03, 2022-04
Deployment: done, deploy, 2022-04, 2022-06
