gantt
dateFormat  YYYY-MM
axisFormat %Y-%m
title Urban Modeling
excludes weekends

section Urban Stormwater Model Development 
20 Urban Catchments Developed:t3dev, 2022-07, 2023-07
section Urban Stormwater Model Validation
20 Urban Catchments Validated:t3dev, 2022-12, 2024-05