version: '3.4'

services:
  
  docs:
    build:
      context: ../../
      dockerfile: ./src/docker/docs/Dockerfile
    container_name: docs4${COMPOSE_PROJECT_NAME}
    environment:
      - VIRTUAL_HOST=docs.${HOST_DOMAIN}

  slides:
    build:
      context: ../../
      dockerfile: ./src/docker/slides/Dockerfile
    container_name: slides4${COMPOSE_PROJECT_NAME}
    environment:
      - VIRTUAL_HOST=slides.${HOST_DOMAIN}

networks:
  default:
    external:
      name: nginx-proxy
