apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${NAMESPACE}-pv
  namespace: ${NAMESPACE}
spec:
  capacity:
    storage: 10G
  accessModes:
  - ReadWriteMany
  nfs:
    path: /${PROJECT_ID}
    server: 10.115.85.250