apiVersion: v1
kind: Service
metadata:
  name: ${NAMESPACE}-svc
  namespace: ${NAMESPACE}
  annotations:
    cloud.google.com/backend-config: '{"default": "${NAMESPACE}-backendconfig"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: ${NAMESPACE}-app  
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  - name: geoserver
    protocol: TCP
    port: 8080
    targetPort: 8080