- name: Create to Public Network Device 
  hosts: ["robin"]
  gather_facts:
  vars:
    public_device: eth0
    parent_device: eno1

  tasks:

  - name: Create macvlan
    shell: |
      lxc profile create macvlan
      lxc profile device add macvlan {{ public_device }} nic nictype=macvlan parent={{ parent_device }}
    ignore_errors: