###
# Cloudbuild for Documentation
steps:

# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:RATESResearch/RGVFlood
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Install dependencies
- name: python:3.8
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]

- name: python:3.8
  entrypoint: bash
  args: ["-c", "PATH=\"/builder/home/.local/bin:$$PATH\" && echo $$PATH && make html"]

- name: gcr.io/rgvflood/firebase
  args: ['deploy', '--project=waterwizard', '--only=hosting']

availableSecrets:
  secretManager:
  - versionName: projects/rgvflood/secrets/Github/versions/latest
    env: 'SSH_KEY'
